# change the followings to match your Github username and repo name
baseurl: "/wahajsaleem.github.io" # the name of your github repo
url: "https://wahajsaleem.github.io" # the url of your github pages
